import { Inter, Poppins } from 'next/font/google';
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";

const poppins = Poppins({
  weight: ['400', '500', '600'], // Specify the weights you need
  subsets: ['latin'] // Include subsets as necessary
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
    <GoogleOneTap />
      <body className={poppins.className}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
