import React from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { HiPencilSquare } from 'react-icons/hi2';

function EditChapters({ chapter, onUpdate }) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <button
          className="inline-flex items-center justify-center p-1 hover:bg-gray-100 rounded-md transition-colors ml-2"
          aria-label={`Edit chapter ${chapter?.name}`}
        >
          <HiPencilSquare className="h-4 w-4" />
        </button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Edit Chapter</DialogTitle>
          <DialogDescription>Make changes to the chapter content here.</DialogDescription>
        </DialogHeader>
        <div className="py-4">
          <p className="text-sm text-gray-500">
            Chapter editing coming soon. Currently, chapters are generated by AI.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export default EditChapters;
